// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.feed.reaction

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	FeedReactionNSID = "sh.tangled.feed.reaction"
)

func init() {
	util.RegisterType("sh.tangled.feed.reaction", &FeedReaction{})
} //
// RECORDTYPE: FeedReaction
type FeedReaction struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.feed.reaction" cborgen:"$type,const=sh.tangled.feed.reaction"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	Reaction      string `json:"reaction" cborgen:"reaction"`
	Subject       string `json:"subject" cborgen:"subject"`
}
