// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.git.refUpdate

//import (
//	"github.com/bluesky-social/indigo/lex/util"
//)

const (
	GitRefUpdateNSID = "sh.tangled.git.refUpdate"
)

//func init() {
//	util.RegisterType("sh.tangled.git.refUpdate", &GitRefUpdate{})
//} //
// RECORDTYPE: GitRefUpdate
type GitRefUpdate struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.git.refUpdate" cborgen:"$type,const=sh.tangled.git.refUpdate"`
	// committerDid: did of the user that pushed this ref
	CommitterDid string `json:"committerDid" cborgen:"committerDid"`
	// newSha: new SHA of this ref
	NewSha string `json:"newSha" cborgen:"newSha"`
	// oldSha: old SHA of this ref
	OldSha string `json:"oldSha" cborgen:"oldSha"`
	// ref: Ref being updated
	Ref string `json:"ref" cborgen:"ref"`
	// repoDid: did of the owner of the repo
	RepoDid string `json:"repoDid" cborgen:"repoDid"`
	// repoName: name of the repo
	RepoName string `json:"repoName" cborgen:"repoName"`
}
