// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.issue.comment

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoIssueCommentNSID = "sh.tangled.repo.issue.comment"
)

func init() {
	util.RegisterType("sh.tangled.repo.issue.comment", &RepoIssueComment{})
} //
// RECORDTYPE: RepoIssueComment
type RepoIssueComment struct {
	LexiconTypeID string  `json:"$type,const=sh.tangled.repo.issue.comment" cborgen:"$type,const=sh.tangled.repo.issue.comment"`
	Body          string  `json:"body" cborgen:"body"`
	CreatedAt     string  `json:"createdAt" cborgen:"createdAt"`
	Issue         string  `json:"issue" cborgen:"issue"`
	Owner         *string `json:"owner,omitempty" cborgen:"owner,omitempty"`
	Repo          *string `json:"repo,omitempty" cborgen:"repo,omitempty"`
}
