// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.knot.ack

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	KnotAckNSID = "sh.tangled.knot.ack"
)

func init() {
	util.RegisterType("sh.tangled.knot.ack", &KnotAck{})
} //
// RECORDTYPE: KnotAck
type KnotAck struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.knot.ack" cborgen:"$type,const=sh.tangled.knot.ack"`
	// aturi: the at-uri to ack
	Aturi     string `json:"aturi" cborgen:"aturi"`
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// host: the host of the knot that is acking this at-uri
	Host   string `json:"host" cborgen:"host"`
	Status string `json:"status" cborgen:"status"`
}
