// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.pull.patch

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoPullPatchNSID = "sh.tangled.repo.pull.patch"
)

func init() {
	util.RegisterType("sh.tangled.repo.pull.patch", &RepoPullPatch{})
} //
// RECORDTYPE: RepoPullPatch
type RepoPullPatch struct {
	LexiconTypeID string  `json:"$type,const=sh.tangled.repo.pull.patch" cborgen:"$type,const=sh.tangled.repo.pull.patch"`
	Body          *string `json:"body,omitempty" cborgen:"body,omitempty"`
	CreatedAt     *string `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
	Patch         string  `json:"patch" cborgen:"patch"`
	PullId        int64   `json:"pullId" cborgen:"pullId"`
	SourceRepo    *string `json:"sourceRepo,omitempty" cborgen:"sourceRepo,omitempty"`
	TargetRepo    string  `json:"targetRepo" cborgen:"targetRepo"`
	Title         string  `json:"title" cborgen:"title"`
}
