// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.pull.state

import (
	//"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoPullStateNSID = "sh.tangled.repo.pull.state"
)

func init() {
	//util.RegisterType("sh.tangled.repo.pull.state", &RepoPullState{})
} //
// RECORDTYPE: RepoPullState
type RepoPullState struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.repo.pull.state" cborgen:"$type,const=sh.tangled.repo.pull.state"`
	Pull          string `json:"pull" cborgen:"pull"`
	// state: state of the pull request
	State *string `json:"state,omitempty" cborgen:"state,omitempty"`
}
