// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.branches

import (
	"bytes"
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoBranchesNSID = "sh.tangled.repo.branches"
)

// RepoBranches calls the XRPC method "sh.tangled.repo.branches".
//
// cursor: Pagination cursor
// limit: Maximum number of branches to return
// repo: Repository identifier in format 'did:plc:.../repoName'
func RepoBranches(ctx context.Context, c util.LexClient, cursor string, limit int64, repo string) ([]byte, error) {
	buf := new(bytes.Buffer)

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	params["repo"] = repo
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.branches", params, nil, buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
