// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.removeSecret

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoRemoveSecretNSID = "sh.tangled.repo.removeSecret"
)

// RepoRemoveSecret_Input is the input argument to a sh.tangled.repo.removeSecret call.
type RepoRemoveSecret_Input struct {
	Key  string `json:"key" cborgen:"key"`
	Repo string `json:"repo" cborgen:"repo"`
}

// RepoRemoveSecret calls the XRPC method "sh.tangled.repo.removeSecret".
func RepoRemoveSecret(ctx context.Context, c util.LexClient, input *RepoRemoveSecret_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "sh.tangled.repo.removeSecret", nil, input, nil); err != nil {
		return err
	}

	return nil
}
