// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.addSecret

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoAddSecretNSID = "sh.tangled.repo.addSecret"
)

// RepoAddSecret_Input is the input argument to a sh.tangled.repo.addSecret call.
type RepoAddSecret_Input struct {
	Key   string `json:"key" cborgen:"key"`
	Repo  string `json:"repo" cborgen:"repo"`
	Value string `json:"value" cborgen:"value"`
}

// RepoAddSecret calls the XRPC method "sh.tangled.repo.addSecret".
func RepoAddSecret(ctx context.Context, c util.LexClient, input *RepoAddSecret_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "sh.tangled.repo.addSecret", nil, input, nil); err != nil {
		return err
	}

	return nil
}
