// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.pull

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoPullNSID = "sh.tangled.repo.pull"
)

func init() {
	util.RegisterType("sh.tangled.repo.pull", &RepoPull{})
} //
// RECORDTYPE: RepoPull
type RepoPull struct {
	LexiconTypeID string  `json:"$type,const=sh.tangled.repo.pull" cborgen:"$type,const=sh.tangled.repo.pull"`
	Body          *string `json:"body,omitempty" cborgen:"body,omitempty"`
	CreatedAt     *string `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
	Patch         string  `json:"patch" cborgen:"patch"`
	PullId        int64   `json:"pullId" cborgen:"pullId"`
	SourceRepo    *string `json:"sourceRepo,omitempty" cborgen:"sourceRepo,omitempty"`
	TargetBranch  string  `json:"targetBranch" cborgen:"targetBranch"`
	TargetRepo    string  `json:"targetRepo" cborgen:"targetRepo"`
	Title         string  `json:"title" cborgen:"title"`
}
