// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.pull

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoPullNSID = "sh.tangled.repo.pull"
)

func init() {
	util.RegisterType("sh.tangled.repo.pull", &RepoPull{})
} //
// RECORDTYPE: RepoPull
type RepoPull struct {
	LexiconTypeID string           `json:"$type,const=sh.tangled.repo.pull" cborgen:"$type,const=sh.tangled.repo.pull"`
	Body          *string          `json:"body,omitempty" cborgen:"body,omitempty"`
	CreatedAt     string           `json:"createdAt" cborgen:"createdAt"`
	Patch         string           `json:"patch" cborgen:"patch"`
	PullId        int64            `json:"pullId" cborgen:"pullId"`
	Source        *RepoPull_Source `json:"source,omitempty" cborgen:"source,omitempty"`
	TargetBranch  string           `json:"targetBranch" cborgen:"targetBranch"`
	TargetRepo    string           `json:"targetRepo" cborgen:"targetRepo"`
	Title         string           `json:"title" cborgen:"title"`
}

// RepoPull_Source is a "source" in the sh.tangled.repo.pull schema.
type RepoPull_Source struct {
	Branch string  `json:"branch" cborgen:"branch"`
	Repo   *string `json:"repo,omitempty" cborgen:"repo,omitempty"`
	Sha    string  `json:"sha" cborgen:"sha"`
}
