// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.pull.status.closed

const (
	RepoPullStatusClosedNSID = "sh.tangled.repo.pull.status.closed"
)

const RepoPullStatusClosed = "sh.tangled.repo.pull.status.closed"
