// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.issue.state.closed

const (
	RepoIssueStateClosedNSID = "sh.tangled.repo.issue.state.closed"
)

const RepoIssueStateClosed = "sh.tangled.repo.issue.state.closed"
