// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.pull.state.merged

const ()

const RepoPullStateMerged = "sh.tangled.repo.pull.state.merged"
