// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.pull.state.open

const ()

const RepoPullStateOpen = "sh.tangled.repo.pull.state.open"
