// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.pull.state.closed

const ()

const RepoPullStateClosed = "sh.tangled.repo.pull.state.closed"
