// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.pull.status.closed

const ()

const RepoPullStatusClosed = "sh.tangled.repo.pull.status.closed"
