// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.pull.status.open

const (
	RepoPullStatusOpenNSID = "sh.tangled.repo.pull.status.open"
)

const RepoPullStatusOpen = "sh.tangled.repo.pull.status.open"
