// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.pull.status.merged

const (
	RepoPullStatusMergedNSID = "sh.tangled.repo.pull.status.merged"
)

const RepoPullStatusMerged = "sh.tangled.repo.pull.status.merged"
