// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.string

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	StringNSID = "sh.tangled.string"
)

func init() {
	util.RegisterType("sh.tangled.string", &String{})
} //
// RECORDTYPE: String
type String struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.string" cborgen:"$type,const=sh.tangled.string"`
	Contents      string `json:"contents" cborgen:"contents"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	Description   string `json:"description" cborgen:"description"`
	Filename      string `json:"filename" cborgen:"filename"`
}
