// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.knot

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	KnotNSID = "sh.tangled.knot"
)

func init() {
	util.RegisterType("sh.tangled.knot", &Knot{})
} //
// RECORDTYPE: Knot
type Knot struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.knot" cborgen:"$type,const=sh.tangled.knot"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
}
