// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.owner

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	OwnerNSID = "sh.tangled.owner"
)

// Owner_Output is the output of a sh.tangled.owner call.
type Owner_Output struct {
	Owner string `json:"owner" cborgen:"owner"`
}

// Owner calls the XRPC method "sh.tangled.owner".
func Owner(ctx context.Context, c util.LexClient) (*Owner_Output, error) {
	var out Owner_Output
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.owner", nil, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
