// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.spindle

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	SpindleNSID = "sh.tangled.spindle"
)

func init() {
	util.RegisterType("sh.tangled.spindle", &Spindle{})
} //
// RECORDTYPE: Spindle
type Spindle struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.spindle" cborgen:"$type,const=sh.tangled.spindle"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
}
